alias hal='ssh martin@hal.tihlde.org'
alias sal='ssh martin@sal.tihlde.org'
alias wopr='ssh martin@wopr.tihlde.org'
alias mellow='ssh foo@debian.mellowland.net'
alias atlantis='ssh martin@atlantis.kverka.no'
alias colargol='ssh martinop@colargol.tihlde.org'
alias gremlin='ssh martinop@gremlin.stud.aitel.hist.no'
alias gw='ssh root@gw'

alias up2date='sudo apt-get update && sudo apt-get upgrade'
alias mount_mp3='sshfs -o ro,allow_other martin@wopr.tihlde.org:/glftpd/site/archive/mp3 ~/Music'
alias umount_mp3='fusermount -uz ~/Music'
alias backup_local='rsync --archive --delete --verbose --exclude=hlds --exclude=Steam --exclude=rtorrent martin@sal.tihlde.org:~ ~/rsync'
alias backup_mp3='rsync --archive --delete --verbose martin@wopr.tihlde.org:/glftpd/site/archive/array1/mp3 /media/PASSPORT/loot/'
alias backup_mp3_lap='rsync --archive --delete --verbose martin@wopr.tihlde.org:/glftpd/site/archive/array1/mp3/ ~/Music/'
alias backup_push='rsync --archive --delete --exclude=rsync --exclude=Music --exclude=.cache --verbose ~/ martin@sal.tihlde.org:~/rsync/hax'
alias dns2tcpc='~/dns2tcp/bin/dns2tcpc'
alias sshproxy='ssh -D 8080 -C -N martin@172.16.0.1'
alias iodine='sudo ~/iodine/bin/iodine -f -P Qu5haN8freSPeyU9 m.pythonic.eu'
alias iodine_test='sudo ~/iodine/bin/iodine -f -r -P Qu5haN8freSPeyU9 195.159.0.100 m.pythonic.eu'

alias ls='ls --color=auto'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

alias pacclean='sudo pacman -Rs $(pacman -Qdt | awk '"'"'{print $1}'"'"' | xargs)'
alias pacup='sudo pacman -Syu --ignore=kernel26'
alias pacwipe='sudo pacman -Rns'
alias pkg_info='dpkg --list | tail --lines=+6 | awk '\''{print $2}'\'''
alias l4d_up='~/hlds/steam -command update -game l4d_full -dir ~/hlds'
alias l4d_cfg='vim ~/hlds/l4d/left4dead/cfg/server.cfg'
alias l4d_start='cd ~/hlds/l4d && ./srcds_run +ip 158.38.48.15'
alias l4d2_up='~/hlds/steam -command update -game left4dead2 -dir ~/hlds'
alias l4d2_cfg='vim ~/hlds/left4dead2/left4dead2/cfg/server.cfg'
alias l4d2_start='cd ~/hlds/left4dead2 && ./srcds_run +ip 158.38.48.15'
alias pftp='~/pftp/pftp.sh'
alias iodined='sudo ~/iodine/bin/iodined -f -u nobody -t /var/empty -c -P Qu5haN8freSPeyU9 172.16.0.1 m.pythonic.eu'
alias sitebot='telnet localhost 45000'

