# Package management
alias aptup='sudo apt-get update && sudo apt-get upgrade'
alias pacsyu='sudo pacman-color -Syu --ignore=kernel26'
alias pacrns='sudo pacman-color -Rns'
alias pacqdt='pacman-color -Qdt'
alias pacqi='pacman-color -Qi'
alias pacql='pacman-color -Ql'
alias pacss='pacman-color -Ss'
alias pacqm='pacman-color -Qm'
alias pacs='sudo pacman-color -S'
alias clysyu='sudo clyde -Syu --ignore=kernel26 --aur'
alias clyss='clyde -Ss'
alias clys='sudo clyde -S'
alias clyqm='clyde -Qm'
